name: Publish getting-started-app if changed

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - spec/**
      - Dockerfile
      - package.json
      
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v4

      - name: "🔧 setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "📦 install dependencies"
        uses: bahmutov/npm-install@v1

      # - name: "📦 build getting-started-app"
        # run: npx build-getting-started-app

      - name: Verify app
        run: npm test --if-present

      - name: "🚀 deploy static"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./getting-started-app-static
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false
